syms g I l lc m ...
q1(t) q2(t) q3(t) ...
q1_dot(t) q2_dot(t) q3_dot(t) ...
q1_Ddot(t) q2_Ddot(t) q3_Ddot(t) ...
z1(t) z2(t) ...
z1_dot(t) z2_dot(t) ...
z1_Ddot(t) z2_Ddot(t) 

q = [ q1(t) q2(t) q3(t) ];
q_dot = [ q1_dot(t) q2_dot(t) q3_dot(t) ];
q_Ddot = [ q1_Ddot(t) q2_Ddot(t) q3_Ddot(t) ];

z = [ z1(t) z2(t) ];
z_dot = [ z1_dot(t) z2_dot(t) ];
z_Ddot = [ z1_Ddot(t) z2_Ddot(t) ];
